# Site settings
title: Creative Commons Global Summit 2015
email: creative@cckorea.org
url: http://localhost:4000
description: "Creative Commons Global Summit 2015"
image: header-title.png

twitter_username: cckorea
github_username:  creativecommonskorea

# Build settings
markdown: kramdown
permalink: pretty
