# Site settings
title: CC Global Summit 2015
email: ccgs2015.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Creative Commons Global Summit is a global festival
    which is organized and programmed not only from each summit´s host country
    but from many global CC affiliates over the world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://summit.cckorea.org" # the base hostname & protocol for your site
locale: ko_KR
default_banner: '/images/base/title.png'

# Build settings
markdown: kramdown
encoding: UTF-8
exclude: ['*.bak']
sass:
  style: compressed

# collections
collections:
  sessions:
    output: true
    permalink: /session/:name.html

defaults:
  - scope:
      path: "session"
      type: "sessions"
    values:
      layout: "session"
